import { Plugin } from 'vue'

export const MYMessage: (options: string | { message: string | import('vue').VNode; duration?: number; showClose?: boolean; offset?: number }) => { id: number; close: () => void }
export const MYMessageComponent: any

declare const MengyuePlus: Plugin
export default MengyuePlus
export * from './button'
export * from './border'
export * from './text'
export * from './a'
export * from './scroll'
export * from './scrollbar'
export * from './container'
export * from './layout'
export * from './input'
export * from './radio'
export * from './checkbox'
export * from './switch'
export * from './rate'
export * from './pickColor'
export * from './selectDate'
export * from './selectTime'
export * from './select'
export * from './selectCascader'
export * from './sliderbar'
export * from './form'
export * from './badge'
export * from './collapse'
export * from './progress'
export * from './result'
export * from './skeleton'
export * from './pagination'
export * from './table'
export * from './timeline'
export * from './tree'
export * from './backtop'
export * from './breadcrumb'
export * from './dropdown'
export * from './menu'
export * from './step'
export * from './carousel'
export * from './transfer'
export * from './alert'